# Generated by Django 4.0.5 on 2022-07-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_eventmodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='picture',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
    ]
